### ISSUE TITLE
Dropdown trigger submits form

### ISSUE THREAD

**Issue by tipuban** [tanansatpal/ngx-mat-intl-tel-input#1]
When placed inside a form tag, the dropdown trigger will submit the form (the trigger button should have a type="button" attribute). 

From the W3C spec:

>  - submit: This is the default if the attribute is not specified, or if the attribute is dynamically changed to an empty or invalid value.

Thanks!

**Comment by matthewmullin01** [comment]
I am also having the same problem.

The component template code in this repo has type="button", so I am not sure if the npm package has just not been update, or somehow when building the package this information is lost.

A solution for now is in your component.ts just add the following code to set the button type manually.

```
document.getElementsByClassName('country-selector')[0].type = 'button';
```

**Comment by tipuban** [comment]
Thanks a lot for the fixes! Closing issue.

**Comment by matthewmullin01** [comment]
@tipuban Sure!

I think the issue should remain open.

My solution is merely a workaround for the time being. I forked the project to try fix the issue, but I do not see where the bug exactly is.

**Comment by tanansatpal** [comment]
I have updated the build on npm. Now you should be able to use the form submit without the workaround
