### ISSUE TITLE
country searchable

### ISSUE THREAD

**Issue by vaibhavpatil111** [tanansatpal/ngx-mat-intl-tel-input#12]
How to make country dropdown searchable ?

**Comment by tanansatpal** [comment]
Hi @vaibhavpatil111 , I am working on that. Will be available in the next release. But I am not getting that much time currently. Maybe you could try something and everything fits, send a PR and I will happily merge it.

**Comment by Joseph-LeGrand** [comment]
Can you perhaps push the code you have to a branch? I could provide input as I'm trying to implement that

**Comment by skidvd** [comment]
FYI, there is an existing PR here: [PR#14](https://github.com/tanansatpal/ngx-mat-intl-tel-input/pull/14) that looks promising.

**Comment by tanansatpal** [comment]
Hi @all, the PR related to this issue has been merged and available in version 2.0.3

**Comment by skidvd** [comment]
Hi Satpal,

Thank you for your email and merging this!

I would like to ask you about one other issue I have with this component?
 Upon first display of the component with an existing phone number, the
country selected is not correct - it appears to always be Afghanistan +93.
Once I select/focus the control, the country code "adjusts" and becomes
correct for the exiting number, but not until after that selection (which
may never happen if the user has no need to change it).  I have noted the
[enableAutoCountrySelect]="true"  parameter, but it appears to have no
effect regardless of value - at least as far as initial display is
concerned?  Lastly, as an FYI in our case, we are not using either the
defaultCountry or allowedCountries values as there are no such values for
our application - any and all countries are acceptable.

Did you happen to bump into this and find a good solution?

Thanks again,

Todd
