### ISSUE TITLE
 Can't bind to 'readOnly' since it isn't a known property of 'ngx-mat-intl-tel-input'.

### ISSUE THREAD

**Issue by rashid-naico** [tanansatpal/ngx-mat-intl-tel-input#126]

**Comment by guigeek973mesdocteurs** [comment]
and readonly html version dont work too

**Comment by guigeek973mesdocteurs** [comment]
please add an input for readonly phone number :D

**Comment by tanansatpal** [comment]
We can use disabled instead of readOnly. They have the same behaviour. This is still a pending item with Angular itself: https://github.com/angular/angular/issues/11447

Closing this for now, as it would not be implemented.
