### ISSUE TITLE
Accessibility: Is there a way to set input element's aria-describedby value?

### ISSUE THREAD

**Issue by hansknowyou** [tanansatpal/ngx-mat-intl-tel-input#130]
The current describedBy value seems to be not used.

**Comment by venraij** [comment]
This pull request adds it but i dont think the mantainer is active https://github.com/tanansatpal/ngx-mat-intl-tel-input/pull/132

**Comment by venraij** [comment]
You can temporarily use this if you want https://www.npmjs.com/package/ngx-mat-intl-tel-input-angular-13 it has the describedBy integrated

**Comment by tanansatpal** [comment]
Available in v4.1.0 now.
