### ISSUE TITLE
Breaks in angular 13

### ISSUE THREAD

**Issue by ganySA** [tanansatpal/ngx-mat-intl-tel-input#131]
Hi 

Numerous breakages in Angular 13 for those who are testing.

rror: node_modules/ngx-mat-intl-tel-input/lib/ngx-mat-intl-tel-input.component.d.ts:10:31 - error TS2305: Module '"@angular/material/core"' has no exported member 'CanUpdateErrorStateCtor'.

10 import { CanUpdateErrorState, CanUpdateErrorStateCtor, ErrorStateMatcher } from '@angular/material/core';
                                 ~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ngx-mat-intl-tel-input/lib/ngx-mat-intl-tel-input.component.d.ts:24:22 - error TS2420: Class 'NgxMatIntlTelInputComponent' incorrectly implements interface 'CanUpdateErrorState'.
  Type 'NgxMatIntlTelInputComponent' is missing the following properties from type 'CanUpdateErrorState': updateErrorState, errorState

24 export declare class NgxMatIntlTelInputComponent extends _NgxMatIntlTelInputMixinBase implements OnInit, OnDestroy, DoCheck, CanUpdateErrorState, MatFormFieldControl<any> {
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~

Error: node_modules/ngx-mat-intl-tel-input/lib/ngx-mat-intl-tel-input.component.d.ts:24:22 - error TS2720: Class 'NgxMatIntlTelInputComponent' incorrectly implements class 'MatFormFieldControl<any>'. Did you mean to extend 'MatFormFieldControl<any>' and inherit its members as a subclass?
  Property 'errorState' is missing in type 'NgxMatIntlTelInputComponent' but required in type 'MatFormFieldControl<any>'.

24 export declare class NgxMatIntlTelInputComponent extends _NgxMatIntlTelInputMixinBase implements OnInit, OnDestroy, DoCheck, CanUpdateErrorState, MatFormFieldControl<any> {
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/@angular/material/form-field/form-field-control.d.ts:37:14
    37     readonly errorState: boolean;
                    ~~~~~~~~~~
    'errorState' is declared here.

**Comment by venraij** [comment]
I have opened a pull request that fixes the issue https://github.com/tanansatpal/ngx-mat-intl-tel-input/pull/132

Just waiting for it to be merged

**Comment by venraij** [comment]
@ganySA you can temporarily use https://www.npmjs.com/package/ngx-mat-intl-tel-input-angular-13 untill it gets merged

**Comment by tanansatpal** [comment]
Hi @ganySA , the new version 4.1.0 is released which supports Angular 13.
