### ISSUE TITLE
Cannot reset control value on form.reset()

### ISSUE THREAD

**Issue by punit-singh999** [tanansatpal/ngx-mat-intl-tel-input#20]
the control not getting reset after calling form.reset().  
is there way to clear value from the control and reset it?

**Comment by tanansatpal** [comment]
Hi @punit-singh999 , the issue is fixed in the latest version. Please update to the latest version.

**Comment by shivam0dot7** [comment]
I am facing the same issue again in version 3.1.0 (latest). Could you please let me know the solution or some workaround to it. Working on a high priority task!
