### ISSUE TITLE
Invalid input when control form is touched and dirty and value is null

### ISSUE THREAD

**Issue by Kookaburra54** [tanansatpal/ngx-mat-intl-tel-input#24]
Hi ! Thanks for your work, this library does the job pretty well. However, I think that the validation might be improved a little bit as mentioned in the title : when the control form becomes touched and dirty but the input value is null, the status remains invalid eventhough the control is not required, which thus prevents from submitting the form.

For any useful purpose, hereafter is how I use it in my HTML code:
`        <mat-form-field style="min-width: 300px;">
          <ngx-mat-intl-tel-input
          name="mobileNumber"
          [enablePlaceholder]="true"
          placeholder="{{'common.table.mobile-phone' | translate}}"
          formControlName="mobileNumber"
          #mobileNumber>
          </ngx-mat-intl-tel-input>
        </mat-form-field>`

**Comment by EFFKAY2** [comment]
[https://github.com/tanansatpal/ngx-mat-intl-tel-input/pull/47](url)

Should fix this

**Comment by tanansatpal** [comment]
Fixed in #49 . Will be merging and publishing it shortly
