### ISSUE TITLE
ERROR TypeError: "this.phoneNumber is null"

### ISSUE THREAD

**Issue by BillDavid07** [tanansatpal/ngx-mat-intl-tel-input#27]
on select country flag with empty phone field value it returns an error on console.

ERROR TypeError: "this.phoneNumber is null"
    _getFullNumber ngx-mat-intl-tel-input.js:594
    onPhoneNumberChange ngx-mat-intl-tel-input.js:649
    onCountrySelect ngx-mat-intl-tel-input.js:656

**Comment by gchronos** [comment]
+1

**Comment by gchronos** [comment]
ok found 
it's because we using *, [Validators.required]*
and looks like because of this we have one extra onchange event

so don't use extra validators with this plugin (at least for now)

**Comment by BillDavid07** [comment]
Ok thanks @gchronos :)
