### ISSUE TITLE
US and Canada 

### ISSUE THREAD

**Issue by jberg2016** [tanansatpal/ngx-mat-intl-tel-input#3]
I noticed that if US and Canada are options, the component does not know how to distinguish between the two country codes when initializing the input. 

For example, if I select US, enter a valid number and submit. Then reset my form and initialize the value to the saved value. The input shows Canada as the selected country instead of US.

Is there anyway fix this?

Thank you

**Comment by tanansatpal** [comment]
Closing this as it is fixed

**Comment by poliquinp** [comment]
I use version 4.1.0 because my app is on Angular 13.3.0 and if I enter a Canadian number  1-887-###-#### it still gives USA flag.

**Comment by sbnagane** [comment]
> I use version 4.1.0 because my app is on Angular 13.3.0 and if I enter a Canadian number 1-877-###-#### it still gives USA flag.

did you solve this issue ?

**Comment by sbnagane** [comment]
> Canada

did you solve this issue ?
