### ISSUE TITLE
Placeholder is missing in the input / matInput

### ISSUE THREAD

**Issue by wratte** [tanansatpal/ngx-mat-intl-tel-input#35]
The placeholder parameter is missing in the input.

Ex:

  <input matInput type="tel" autocomplete="off"
         [ngClass]="cssClass"
         (blur)="onTouched()"
         (keypress)="onInputKeyPress($event)"
         [(ngModel)]="phoneNumber"
         (ngModelChange)="onPhoneNumberChange()"
         [errorStateMatcher]="errorStateMatcher"
         [disabled]="disabled" #focusable>

There should be a placeholder with param here.

Thanks

**Comment by sandra023** [comment]
think you might have left this in the wrong place. This is for ngx-mat-intl-tel-input. Also, all you have to do is type in [placeholder] = "you placeholder here"

**Comment by wratte** [comment]
Hello Sandra, I'm actually referencing this project 'ngx-mat-intl-tel-input'.

I tried to use the placeholder field expecting to have a placeholder text on in the input text field.
Unfortunatly there is no place holder displayed. I had a look in this project code and found out that in the following file there is no placeholder param in the input tag.
ngx-mat-intl-tel-input/projects/ngx-mat-intl-tel-input/src/lib/ngx-mat-intl-tel-input.component.html
line 25.

I figured out that what your guys call a placehold is actually the <mat-label> tag.

For the <mat-form-field appearance="outline"> it is mandatory to have placeholder parameter on the tag, else it won't work.

Could you please have a look at it and if possible to add the placeholder param in the input.

Material refenrece: 
https://stackblitz.com/angular/malkplgnkdb?file=src%2Fapp%2Fform-field-appearance-example.html

I also created a a stackblitz with this project to show the difference.

https://stackblitz.com/edit/angular-kfigu2?file=src%2Fapp%2Fapp.component.html

Thanks

**Comment by tanansatpal** [comment]
HI @wratte , I will be checking the same.

**Comment by wratte** [comment]
Hi tranansatpal, Any feedback for this issue? Thanks

**Comment by tanansatpal** [comment]
Hi @wratte , looking at the stackblitz that you shared, I don't think the placeholder is necessary. You just have to pass the text that you want, in the <mat-label> tag instead of place holder and it would work the same way i.e float like the label.
E.g. for the below code

      <mat-form-field style="width:50%" appearance="outline">
        <mat-label>Enter Number</mat-label>
        <ngx-mat-intl-tel-input
        [cssClass]="'custom'"
        [preferredCountries]="['us', 'ca']"
        [enablePlaceholder]="true"
        placeholder="Enter Number"
        name="phone"
        formControlName="phone" #phone></ngx-mat-intl-tel-input>
    </mat-form-field>`

I would render something like this

<img width="687" alt="Screenshot 2020-06-01 at 1 13 25 AM" src="https://user-images.githubusercontent.com/20103208/83361263-1bd38600-a3a5-11ea-8d36-1cbe867bd8b5.png">

which would become the below when you click on that

<img width="682" alt="Screenshot 2020-06-01 at 1 13 53 AM" src="https://user-images.githubusercontent.com/20103208/83361278-3a398180-a3a5-11ea-96ff-864012c02f8c.png">

So, you just have to pass the text in the mat-label. I think this resolves your query, else we can check for other options

**Comment by wratte** [comment]
Hello, 
I tried with the with the mat-lable before but unfortunatly there is a bug with you start typing and then move focus out. It overlap the input.

![image](https://user-images.githubusercontent.com/8438094/84403208-6f2eab00-abd3-11ea-8b0a-69adcadc21a3.png)

**Comment by wratte** [comment]
I updated the Stackbliz to include the mat-lable

https://stackblitz.com/edit/angular-kfigu2?file=src%2Fapp%2Fapp.component.html

**Comment by tanansatpal** [comment]
Hi @wratte can you check the behavior with the latest release. I am not able to reproduce it with the latest release.

When it is not selected, it shows the same
<img width="724" alt="Screen Shot 2020-08-20 at 1 32 01 AM" src="https://user-images.githubusercontent.com/20103208/90684072-2ce5b200-e285-11ea-8639-f4d562c765e4.png">

and when I type and lose the focus, then also the label doesn't come down.
<img width="718" alt="Screen Shot 2020-08-20 at 1 32 12 AM" src="https://user-images.githubusercontent.com/20103208/90683984-0aec2f80-e285-11ea-8785-f71a206ef764.png">

**Comment by tanansatpal** [comment]
Hi @wratte , does the latest release solve this issue?

**Comment by wratte** [comment]
Hi @tanansatpal ,

It now works perfectly. Thank you for the time spent on this issue. It's well apreciated.

**Comment by tanansatpal** [comment]
Glad to hear it @wratte
