### ISSUE TITLE
ngcc fails at NgxMatIntlTelInputModule import

### ISSUE THREAD

**Issue by GeorgeKnap** [tanansatpal/ngx-mat-intl-tel-input#39]
using the [ngcc compilation](https://angular.io/guide/ivy#speeding-up-ngcc-compilation)  throws error at `NgxMatIntlTelInputModule` module imports:
![Capture](https://user-images.githubusercontent.com/11920691/74595101-0167dd80-503e-11ea-9fc7-79309ec8c17d.PNG)

relates to updating to project Angular 9

**Comment by maheshchari** [comment]
I am facing same issue, while updating angular 9

**Comment by lasserg** [comment]
Same here.

**Comment by WayneBarnard** [comment]
After upgrading to Angular 9 I also get this error ;(

**Comment by encodia** [comment]
The same here

**Comment by lasserg** [comment]
It seems to be an issue with the new way you import @angular/material modules.  A fix here would be greatly appreciated.

**Comment by Herzenkin** [comment]
Seems the PR  #37 opened 10 days ago should fix this problem

**Comment by maheshchari** [comment]
Mean while we can use fixed new npm module as npm i ngx9-mat-intl-tel-input , if any one publish modified library?

**Comment by PSoltes** [comment]
What is ETA for approving PR #37  ?

**Comment by WayneBarnard** [comment]
Any news on this?

**Comment by tanansatpal** [comment]
The PR #37 is already merged and seems to fix the issue, hence closing the issue.
