### ISSUE TITLE
I dont set default value

### ISSUE THREAD

**Issue by cihancelen** [tanansatpal/ngx-mat-intl-tel-input#4]
I've used in my angular project. I don't set default value.
And error 
ERROR TypeError: Cannot read property 'country' of undefined
    at NgxMatIntlTelInputComponent.push../node_modules/ngx-mat-intl-tel-input/fesm5/ngx-mat-intl-tel-input.js.NgxMatIntlTelInputComponent.writeValue (ngx-mat-intl-tel-input.js:693)
    at setUpControl (forms.js:2057)

**Comment by tanansatpal** [comment]
Hi @cihancelen ,
This error could only be triggered when you have passed some default value. Might be in your case instead of a blank string you must have sent a **space** in the string. Till the time it is not fixed, you could send a blank string instead of a space in the string.

**Comment by tanansatpal** [comment]
Fixed in the latest release 2.0.2
