### ISSUE TITLE
Issue with reset on nigerian mobile entry

### ISSUE THREAD

**Issue by otejiri** [tanansatpal/ngx-mat-intl-tel-input#43]
The input resets on 8 digits that is before it gets to the complete Nigerian mobile number which is 11 digits

So I did a little edit on the ngx-mat-intl-tel-input.js file to fix this

     if (numberInstance.nationalNumber.length > 10) {
         return error;
        }
        if (numberInstance && !numberInstance.isValid()) {
            if (numberInstance.nationalNumber.length > 10) {
                return error;
            }

**Comment by mshubhamtyagi** [comment]
Hi @otejiri I am also facing same issue but for Iranian user.

**Comment by tanansatpal** [comment]
Hi @otejiri @mshubhamtyagi , this issue is fixed in the PR #49 .
I will be merging it shortly, if you guys can check with the updated branch whether it fixes your issues or not.

**Comment by tanansatpal** [comment]
#49
