### ISSUE TITLE
I'am changing input field value and I'am deleting this value. But form field invalid still. 

### ISSUE THREAD

**Issue by yldzmamak** [tanansatpal/ngx-mat-intl-tel-input#45]
I'am changing input field value and I'am deleting this value. But form field invalid still. Can you please update? Or can you share the onChange function to see if it's empty

**Comment by EFFKAY2** [comment]
[https://github.com/tanansatpal/ngx-mat-intl-tel-input/pull/47](url)

Should fix this

**Comment by tanansatpal** [comment]
Fixed in #49 . Will be merging and publishing it shortly.
