### ISSUE TITLE
MaxLegnth

### ISSUE THREAD

**Issue by jberg2016** [tanansatpal/ngx-mat-intl-tel-input#5]
Hi,

Is there anyway to restrict the max length of input?

I noticed that validation breaks after entering a lot of characters. 

For example : 

6023346543 is valid US number - correct

60233465433 is invalid US number - correct

602334654332223345 is some how valid - not correct

Is there anyway of restricting max input to like 15 or x amount of digits?

Thank you

**Comment by SeppeD** [comment]
You can use a validator when you create the form: new FormControl('', Validators.maxLength(15)).

`this.telephoneForm = this.formBuilder.group({
        telephone: ['', Validators.maxLenght(15)],
    }
);`

**Comment by jberg2016** [comment]
Thank you taking the time to reply.

I have tried using maxLength(15) validator on the form control. However, there seems to be a strange issue after you reach a certain length.

For example, if you type in the following 17 characters 55555555555555555 the validator works fine up until the 18th character. When you type in the 18th character, somehow the validator passes.

Have you experienced the same issue?

**Comment by tanansatpal** [comment]
Hi @jberg2016 ,
I tried with the numbers given by you and found the issue you are encountering. 
The way the component works is, it tries to get the possible number from the user input based on some regexes. 
If it is valid then it goes to the Validator to check whether the number is actually correct or not based on the country selected and triggers the validation validatePhoneNumber
If no possible number could be found in the user input, then the Model is cleared and **validator is not executed**, instead the value is cleared.

Will be fixing it in a new version, till then if possible you could make the field required and trigger the required error message.

**Comment by tanansatpal** [comment]
Fixed in the latest release 2.0.2
