### ISSUE TITLE
You could put @input string that changes the placeholder of the search input, to be able to customize it, it would be very helpful, thanks.

### ISSUE THREAD

**Issue by marwilc** [tanansatpal/ngx-mat-intl-tel-input#54]

**Comment by GeriCyber** [comment]
This it will be very useful for translate the 'search' text in the search field

**Comment by tanansatpal** [comment]
Can we have some more info regarding this change. Maybe some example

**Comment by begandroide** [comment]
Hi all! the PR https://github.com/tanansatpal/ngx-mat-intl-tel-input/pull/64 maybe could be a help for this problem.

Regards!

**Comment by tanansatpal** [comment]
Hi @begandroide I have merged the PR. Will create a release shortly.
Thanks for the help

**Comment by tanansatpal** [comment]
This is merged in the latest release 3.2.1.
