### ISSUE TITLE
Possibility to format phone number ? 

### ISSUE THREAD

**Issue by Tristan-DELMAS** [tanansatpal/ngx-mat-intl-tel-input#58]
I may miss something, but I don't see any option to format the number on display. This make the readibility uneasy. 

![Capture](https://user-images.githubusercontent.com/48434708/88271886-25f46f80-ccd8-11ea-9edd-184ea673f6d1.PNG)

Could we have the option to see it as a formatNational inside the input ?

**Comment by tanansatpal** [comment]
@Tristan-DELMAS this is implemented in the latest release by @Kichrum. Please check and close the issue, if everything is fine
