### ISSUE TITLE
Country Flags missplaced 

### ISSUE THREAD

**Issue by hansbrito** [tanansatpal/ngx-mat-intl-tel-input#59]
Hi! Thanks for this Lib!

Can you guys check if the Flags are missplaced only here ?

![image](https://user-images.githubusercontent.com/10194128/88470624-08402980-ced5-11ea-943c-5c44a6b6121d.png)

Thanks Again!

**Comment by tanansatpal** [comment]
This is fixed in the release version 3.2.0 and the flags should be in the middle now.
