### ISSUE TITLE
Could use a Class for the input panel

### ISSUE THREAD

**Issue by nicuvlad7** [tanansatpal/ngx-mat-intl-tel-input#63]
The .mat-menu-panel that is opened with the country list, i need to style it so that it only shows a few countries, but i also have many other panels like that one, and there is no specific class to style it.
Having multiple phonenumbers on the same form also doesn't help because i can't use the Id either.

the only classes that i can see on that menu are : **mat-menu-panel ng-trigger ng-trigger-transformMenu ng-tns-c217-265 mat-menu-after ng-star-inserted mat-elevation-z4 mat-menu-above**

**Comment by tanansatpal** [comment]
#65 fixes this, as this provides you the component itself and you can add your own class to the matMenu. The example shows the usage for that
