### ISSUE TITLE
Bump Version

### ISSUE THREAD

**Issue by pixelmixer** [tanansatpal/ngx-mat-intl-tel-input#66]
There are a few fixes that have been merged to master in the last few weeks that solve some of the issues in my current project. At the moment I'm referencing master directly, but I'd prefer to just use the latest version. If possible, it would be nice to see a new release so it can be installed via npm.

**Comment by tanansatpal** [comment]
Hi @pixelmixer , the new release 3.2.1 has all the changes from the master.
