### ISSUE TITLE
Selected country doesn't stay on the input

### ISSUE THREAD

**Issue by avikothari** [tanansatpal/ngx-mat-intl-tel-input#9]
I have implemented the library but when I select a country code it's value is not getting selected. I have set the field as required.
![Issue](https://user-images.githubusercontent.com/16880736/59674810-a72e2880-91e1-11e9-9ae9-87682e9164da.png)

**Comment by tanansatpal** [comment]
Hi @avikothari , 
Could you please make a fiddle or a stackblitz to show the error and it is not reproducible at my end. I will try to check for other cases, but the UI seems a little off and different from the one the library provides.

**Comment by tanansatpal** [comment]
Hi @avikothari , could you confirm that it is still not working.

**Comment by avikothari** [comment]
Hi Satpal,

It's working properly!!

**Comment by avikothari** [comment]
And sorry for the late reply.... I just saw this mail thread today.
Apologies

**Comment by tanansatpal** [comment]
Closing this issue as it is fixed

**Comment by skidvd** [comment]
Perhaps I am experiencing a different issue entirely.  However, when I set the value of an existing phone number via the FormBuilder during reactive form creation, the country selection does not match the phone number with the PR I mentioned above.
